#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/root/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/root/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/root/Dropbox/Geoflly/Models/Slice Network/x86_64/x86_64/.libs/libnrnmech.so" "$@"
